# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"em": "06_experiment.ipynb",
         "parameters": "06_experiment.ipynb",
         "other_parameters": "06_experiment.ipynb",
         "ExampleExperimentManager": "07_example_wrapper.ipynb",
         "root_path": "07_example_wrapper.ipynb"}

modules = ["experiment.py",
           "example_wrapper.py"]

doc_url = "https://jaume-jci.github.io/jaume_nbdev/jaume_nbdev/"

git_url = "https://github.com/Jaume-JCI/hpsearch/tree/master/"

def custom_doc_links(name): return None
