# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"em": "06_experiment.ipynb",
         "parameters": "06_experiment.ipynb",
         "other_parameters": "06_experiment.ipynb",
         "ExampleExperimentManager": "07_example_wrapper.ipynb",
         "my_function": "07_example_wrapper.ipynb",
         "write_some": "07_example_wrapper.ipynb",
         "print_util": "hp_util.ipynb"}

modules = ["experiment.py",
           "example_wrapper.py",
           "tools/hp_util.py"]

doc_url = "https://jaume-jci.github.io/jaume_nbdev/hpsearch/"

git_url = "https://github.com/Jaume-JCI/hpsearch/tree/master/"

def custom_doc_links(name): return None
