# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_tests/tools/tst.query.ipynb (unless otherwise specified).

__all__ = ['test_do_query_and_show', 'test_do_query_and_show_change_metric', 'test_do_query_and_show_with_conditions',
           'test_do_query_and_show_sort_maximum', 'test_do_query_and_show',
           'test_parse_arguments_and_query_change_metric', 'test_parse_arguments_and_query_with_conditions']

# Cell
import pytest
import pandas as pd
import os
import joblib
from IPython.display import display
from block_types.utils.nbdev_utils import md

from hpsearch.tools.query import *
from hpsearch.examples.dummy_experiment_manager import generate_data

# Comes from query.ipynb, cell
def test_do_query_and_show ():
    em = generate_data ('do_query_and_show')

    do_query_and_show ()

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_do_query_and_show_change_metric ():
    em = generate_data ('do_query_and_show_change_metric')

    do_query_and_show (metric='test_accuracy')

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_do_query_and_show_with_conditions ():
    em = generate_data ('do_query_and_show_with_conditions')

    do_query_and_show (metric='validation_accuracy', op='max', pf={'epochs':15})

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_do_query_and_show_sort_maximum ():
    em = generate_data ('do_query_and_show_sort_maximum')

    do_query_and_show (metric='validation_accuracy', op='max', sort='max', stats=['mean', 'min', 'max']);

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_do_query_and_show ():
    em = generate_data ('do_query_and_show')

    do_query_and_show ()

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_parse_arguments_and_query_change_metric ():
    em = generate_data ('parse_arguments_and_query_change_metric')

    arg_string = ['--metric', 'test_accuracy']
    parse_arguments_and_query (arg_string)

    em.remove_previous_experiments ()

# Comes from query.ipynb, cell
def test_parse_arguments_and_query_with_conditions ():
    em = generate_data ('parse_arguments_and_query_with_conditions')

    arg_string = ['--metric', 'validation_accuracy',
              '--op', 'max',
              '-f', 'dict(epochs=15)']
    parse_arguments_and_query (arg_string)

    em.remove_previous_experiments ()