# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tools/metric_visualization.ipynb (unless otherwise specified).

__all__ = ['metric_visualization', 'main']

# Cell
import warnings
warnings.filterwarnings('ignore')

import argparse
import sys
sys.path.append('.')
sys.path.append('src')
import pandas as pd
import pickle
import hpsearch.visualization.experiment_visualization as ev
from ..config.hpconfig import get_path_experiments
from ..config.hpconfig import get_default_operations

def metric_visualization (exps=[-1,-2], run_number=0, root_folder=None, metric=None, op = None,
                         parameters=None, name_file='model_history.pk', include_loss=False, backend='visdom'):

    default_operations = get_default_operations ()
    if root_folder is None:
        root_folder = default_operations.get('root', 'results')
    if metric is None:
        metric = default_operations.get('metric', 'accuracy')
    if op is None:
        op = default_operations.get('op', 'min')

    # metrics
    if include_loss:
        metrics = [metric, 'loss']
    else:
        metrics = [metric]

    for i in range(len(exps)):
        if exps[i] == -1:
            root_path = get_path_experiments (folder = root_folder)
            experiment_number = pickle.load(open('%s/current_experiment_number.pkl' %root_path,'rb'))
            exps[i] = experiment_number

        if exps[i] == -2:
            root_path = get_path_experiments (folder = root_folder)
            df = pd.read_csv('%s/experiments_data.csv' %root_path,index_col=0)
            if op=='max':
                exps[i] = df['0_%s' %metric].idxmax()
            else:
                exps[i] = df['0_%s' %metric].idxmin()

    ev.plot_multiple_histories(exps, run_number=run_number, root_folder=root_folder,metrics=metrics,
                                   parameters=parameters, name_file=name_file, backend=backend)

def main():

    parser = argparse.ArgumentParser(description='show metrics about experiments')
    # Datasets
    parser.add_argument('-e', nargs='+', default=[-1, -2], type=int,
                        help="experiments")
    parser.add_argument('--metric', nargs='+', type=str, default=None, help="metrics")
    parser.add_argument('--root', type=str, default=None)
    parser.add_argument('-l','--labels',nargs='+', default=None, type=str)
    parser.add_argument('--run', default=0, type=int)
    parser.add_argument('--op', default=None, type=str)
    parser.add_argument('--backend', default='visdom', type=str)
    parser.add_argument('--file', default='model_history.pk', type=str)

    pars = parser.parse_args()

    ev.plot_multiple_histories(pars.e, run_number=pars.run, root_folder=pars.root, metrics=pars.metric,
                               parameters=pars.labels, name_file=pars.file, backend=pars.backend)


