# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tools/more_runs.ipynb (unless otherwise specified).

__all__ = ['parse_args', 'parse_arguments_and_run', 'main']

# Cell
import argparse
from ..config.hpconfig import get_experiment_manager

# Cell
def parse_args (args):
    parser = argparse.ArgumentParser(description='run experiment')
    parser.add_argument('-d', '--debug', action= "store_true")
    parser.add_argument('-e', '--experiments', type=int, nargs='+', default=None,  help="experiment numbers")
    parser.add_argument('--runs', type=int, default=None,  help="number of runs")
    parser.add_argument('--root', type=str, default=None, help='name of root folder')
    pars = parser.parse_args(args)

    return pars

def parse_arguments_and_run (args):

    pars = parse_args(args)

    other_parameters = dict(
                            use_process=not pars.debug,
                            root_folder=pars.root
                            )

    em = get_experiment_manager ()

    em.rerun_experiment (experiments= pars.experiments, nruns = pars.runs, root_folder=pars.root,
                         other_parameters=other_parameters)

def main():
    parse_arguments_and_run (sys.argv[1:])